name: rust-test.rs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  deployments: write
jobs:
  rust:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      INPUT_TOKEN: ''
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1.16.2
        with:
          name: Rust Benchmark
          tool: 'cargo'
          output-file-path: 'benchmarks.txt'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '1%'
          comment-on-alert: true
          fail-on-alert: true
